### ISSUE TITLE
Flicker

### ISSUE THREAD

**Issue by weirdwiz** [agilephoenix/brick-break#8]
Still not resolved

**Comment by alpha-warrior** [comment]
bro obviosusly it will not
 clear completely ....still its much better NOW

**Comment by alpha-warrior** [comment]
obviously ki spelling aati h

**Comment by weirdwiz** [comment]
Finally merge ho gaya !
Saara code udaya aur phirse likha apna 
check it now

**Comment by alpha-warrior** [comment]
k

**Comment by weirdwiz** [comment]
haa pata hai phew ki spelling galat hai

**Comment by alpha-warrior** [comment]
bro i loved it:)

**Comment by alpha-warrior** [comment]
but its flickering way oo much while it was not doing so without the score

**Comment by weirdwiz** [comment]
reduce diff

**Comment by alpha-warrior** [comment]
REDUCE?
it will make flickering even worse

**Comment by weirdwiz** [comment]
Yes it makes way worse

**Comment by weirdwiz** [comment]
jyada karne pe input lag aa raha

**Comment by alpha-warrior** [comment]
still it can go easily up to 10

**Comment by alpha-warrior** [comment]
you included the user defined options ?

**Comment by alpha-warrior** [comment]
only two wud be enouch that is diff and ball size
..............let me make the difficulty one and you please make the ball size pls.

**Comment by alpha-warrior** [comment]
i am excited do it fast
